package repointel

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// ── Markdown generation ───────────────────────────────────────────────────────

// GenerateRefMD produces a human-readable markdown reference document for the
// repo. Intended for developers to read — includes file contents, conventions,
// and dependency tables.
func GenerateRefMD(entry RepoEntry, mem *RepoMemory, scan *ScanResult) string {
	var sb strings.Builder

	// Header
	sb.WriteString("# " + entry.FullName + "\n\n")
	sb.WriteString(fmt.Sprintf("> Platform: %s · Language: %s · Indexed: %s · SHA: `%s`\n\n",
		entry.Platform,
		nzDefault(mem.PrimaryLang, "unknown"),
		mem.UpdatedAt.UTC().Format("2006-01-02"),
		shortHash(mem.HeadSHA, 8),
	))

	if scan != nil && scan.RiskLevel != "" {
		sb.WriteString(fmt.Sprintf("> **Security risk: %s** — %d CVEs · %d bottlenecks\n\n",
			strings.ToUpper(scan.RiskLevel), len(scan.CVEs), len(scan.Bottlenecks)))
	}

	sb.WriteString("---\n\n")

	// Architecture
	if mem.Architecture != "" {
		sb.WriteString("## Architecture\n\n")
		sb.WriteString(mem.Architecture + "\n\n")
	}

	// Languages
	if len(mem.Languages) > 0 {
		sb.WriteString("## Languages\n\n")
		sb.WriteString(strings.Join(mem.Languages, ", ") + "\n\n")
	}

	// Key files
	if len(mem.KeyFiles) > 0 {
		sb.WriteString("## Key Files\n\n")
		for _, f := range mem.KeyFiles {
			sb.WriteString("- `" + f + "`\n")
		}
		sb.WriteString("\n")
	}

	// Conventions
	if len(mem.Conventions) > 0 {
		sb.WriteString("## Coding Conventions\n\n")
		sb.WriteString("| Convention | Pattern |\n|---|---|\n")
		for _, c := range mem.Conventions {
			sb.WriteString("| " + mdEscape(c.Name) + " | " + mdEscape(c.Pattern) + " |\n")
		}
		sb.WriteString("\n")
	}

	// Dependencies
	if len(mem.Dependencies) > 0 {
		sb.WriteString("## Dependencies\n\n")
		sb.WriteString("| Package | Version | Purpose |\n|---|---|---|\n")
		for _, d := range mem.Dependencies {
			sb.WriteString(fmt.Sprintf("| `%s` | %s | %s |\n",
				d.Name, nzDefault(d.Version, "—"), nzDefault(d.Purpose, "—")))
		}
		sb.WriteString("\n")
	}

	// Test patterns
	if mem.TestPatterns != "" {
		sb.WriteString("## Test Patterns\n\n")
		sb.WriteString(mem.TestPatterns + "\n\n")
	}

	// CI/CD
	if mem.CISummary != "" {
		sb.WriteString("## CI / CD\n\n")
		sb.WriteString(mem.CISummary + "\n\n")
	}

	// Review hints
	if mem.ReviewHints != "" {
		sb.WriteString("## Review Focus\n\n")
		sb.WriteString(mem.ReviewHints + "\n\n")
	}

	// Common issues
	if len(mem.CommonIssues) > 0 {
		sb.WriteString("## Common Issue Patterns\n\n")
		for _, issue := range mem.CommonIssues {
			sb.WriteString("- ⚠ " + issue + "\n")
		}
		sb.WriteString("\n")
	}

	// Operator notes
	if mem.UserContext != "" {
		sb.WriteString("## Operator Notes\n\n")
		sb.WriteString("> " + strings.ReplaceAll(mem.UserContext, "\n", "\n> ") + "\n\n")
	}

	// Security scan
	if scan != nil {
		sb.WriteString("## Security Scan\n\n")
		sb.WriteString(fmt.Sprintf("**Risk level:** %s  \n", strings.ToUpper(scan.RiskLevel)))
		if scan.Summary != "" {
			sb.WriteString("**Summary:** " + scan.Summary + "\n\n")
		}

		if len(scan.CVEs) > 0 {
			sb.WriteString("### CVEs\n\n")
			sb.WriteString("| Severity | Package | Version | Description | CVE IDs |\n|---|---|---|---|---|\n")
			for _, cve := range scan.CVEs {
				ids := strings.Join(cve.CVEIDs, ", ")
				sb.WriteString(fmt.Sprintf("| %s | `%s` | %s | %s | %s |\n",
					cve.Severity, cve.Package,
					nzDefault(cve.Version, "—"),
					mdEscape(cve.Description),
					nzDefault(ids, "—")))
			}
			sb.WriteString("\n")
		}

		if len(scan.Bottlenecks) > 0 {
			sb.WriteString("### Bottlenecks\n\n")
			for _, b := range scan.Bottlenecks {
				sb.WriteString(fmt.Sprintf("**[%s] %s** — %s\n\n", strings.ToUpper(b.Severity), b.Location, b.Description))
				if b.Fix != "" {
					sb.WriteString("> Fix: " + b.Fix + "\n\n")
				}
			}
		}

		if len(scan.Suggestions) > 0 {
			sb.WriteString("### Architecture Suggestions\n\n")
			for _, s := range scan.Suggestions {
				sb.WriteString(fmt.Sprintf("**[%s] %s:** %s\n\n", strings.ToUpper(s.Priority), s.Area, s.Suggestion))
			}
		}
	}

	// Raw source files
	if len(mem.RawFiles) > 0 {
		sb.WriteString("---\n\n## Source Files\n\n")
		for _, rf := range mem.RawFiles {
			ext := filepath.Ext(rf.Path)
			lang := extToLang(ext)
			sb.WriteString("### `" + rf.Path + "`\n\n")
			sb.WriteString("```" + lang + "\n")
			sb.WriteString(rf.Content)
			sb.WriteString("\n```\n\n")
		}
	}

	sb.WriteString("---\n\n")
	sb.WriteString(fmt.Sprintf("*Generated by OpsIntelligence · %s*\n", time.Now().UTC().Format("2006-01-02 15:04 UTC")))
	return sb.String()
}

// GenerateSummaryMD produces a compact, LLM-optimized markdown summary.
// Structured for fast context injection into prompts — no verbose tables or
// raw file content. Designed to be re-read by an LLM on every PR review.
func GenerateSummaryMD(entry RepoEntry, mem *RepoMemory, scan *ScanResult) string {
	var sb strings.Builder

	// Front-matter comment for easy identification
	sb.WriteString(fmt.Sprintf("<!-- REPO INTEL: %s | SHA: %s | Updated: %s -->\n\n",
		entry.ID,
		shortHash(mem.HeadSHA, 8),
		mem.UpdatedAt.UTC().Format("2006-01-02"),
	))

	sb.WriteString("# " + entry.FullName + " — Intelligence Summary\n\n")

	if mem.Architecture != "" {
		sb.WriteString("**Architecture:** " + mem.Architecture + "\n\n")
	}
	if mem.PrimaryLang != "" {
		langs := mem.PrimaryLang
		if len(mem.Languages) > 1 {
			langs += " (" + strings.Join(mem.Languages, ", ") + ")"
		}
		sb.WriteString("**Language:** " + langs + "\n\n")
	}

	if len(mem.Conventions) > 0 {
		sb.WriteString("**Conventions:**\n")
		for _, c := range mem.Conventions {
			sb.WriteString("- " + c.Name + ": " + c.Pattern + "\n")
		}
		sb.WriteString("\n")
	}

	if len(mem.Dependencies) > 0 {
		sb.WriteString("**Key dependencies:**\n")
		for _, d := range mem.Dependencies {
			line := "- " + d.Name
			if d.Version != "" {
				line += " @" + d.Version
			}
			if d.Purpose != "" {
				line += " — " + d.Purpose
			}
			sb.WriteString(line + "\n")
		}
		sb.WriteString("\n")
	}

	if mem.ReviewHints != "" {
		sb.WriteString("**Review focus:** " + mem.ReviewHints + "\n\n")
	}

	if len(mem.CommonIssues) > 0 {
		sb.WriteString("**Common issue patterns:**\n")
		for _, i := range mem.CommonIssues {
			sb.WriteString("- " + i + "\n")
		}
		sb.WriteString("\n")
	}

	if mem.TestPatterns != "" {
		sb.WriteString("**Tests:** " + mem.TestPatterns + "\n\n")
	}

	if mem.CISummary != "" {
		sb.WriteString("**CI/CD:** " + mem.CISummary + "\n\n")
	}

	if scan != nil {
		riskLine := "**Security risk:** " + strings.ToUpper(scan.RiskLevel)
		if len(scan.CVEs) > 0 {
			// Count by severity
			counts := map[string]int{}
			for _, c := range scan.CVEs {
				counts[c.Severity]++
			}
			var parts []string
			for _, sev := range []string{"critical", "high", "medium", "low"} {
				if n := counts[sev]; n > 0 {
					parts = append(parts, fmt.Sprintf("%d %s", n, sev))
				}
			}
			riskLine += " — CVEs: " + strings.Join(parts, ", ")
		}
		sb.WriteString(riskLine + "\n\n")
		if scan.Summary != "" {
			sb.WriteString("**Scan summary:** " + scan.Summary + "\n\n")
		}
	}

	if mem.UserContext != "" {
		sb.WriteString("**Operator notes:** " + mem.UserContext + "\n\n")
	}

	return sb.String()
}

// ── File I/O helpers ──────────────────────────────────────────────────────────

// SaveRefMD writes the ref markdown to disk.
func SaveRefMD(path string, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

// SaveSummaryMD writes the summary markdown to disk.
func SaveSummaryMD(path string, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

// ── Helpers ───────────────────────────────────────────────────────────────────

func nzDefault(s, def string) string {
	if s == "" {
		return def
	}
	return s
}

func shortHash(s string, n int) string {
	if len(s) < n {
		return s
	}
	return s[:n]
}

func mdEscape(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}

func extToLang(ext string) string {
	m := map[string]string{
		".go": "go", ".py": "python", ".js": "javascript", ".ts": "typescript",
		".rs": "rust", ".java": "java", ".rb": "ruby", ".sh": "bash",
		".yaml": "yaml", ".yml": "yaml", ".json": "json", ".toml": "toml",
		".tf": "hcl", ".hcl": "hcl", ".md": "markdown", ".sql": "sql",
		".dockerfile": "dockerfile", ".Dockerfile": "dockerfile",
	}
	if lang, ok := m[ext]; ok {
		return lang
	}
	return ""
}
